#!/usr/bin/env bash

# Vérifier si un argument est fourni
if [ "$#" -ne 1 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Effectuer 5 pings vers l'adresse IP spécifiée
ping -c 5 "$1"
