#!/usr/bin/env bash
# Script that configures an Ubuntu server with specific IP requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1[[:space:]]localhost/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts